services:
  resume-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - ./public:/app/public
    environment:
      - NODE_ENV=development
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_ADMIN
    restart: unless-stopped
    init: true 